<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <PublishAot>false</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LanPong.Tests" />
    <ProjectReference Include="../../src/LanPong/LanPong.csproj" />
  </ItemGroup>
</Project>
