<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="../../src/LanPong/LanPong.csproj" />
    <ProjectReference Include="../../tools/LanPong.BotDiagnostics/LanPong.BotDiagnostics.csproj" />
    <ProjectReference Include="../../tools/LanPong.TrainingData/LanPong.TrainingData.csproj" />
  </ItemGroup>
</Project>
